global:
  external_labels:
      monitor: generic

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: self
    static_configs:
      - targets: ['localhost:9090']

  - job_name: jasmin
    static_configs:
      - targets: ['httpis.chrissx.de:8099']
