name: Build and publish new containers

on:
  push:
    branches: [master]

jobs:
  gcc-x86_64-none-elf-11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-qemu-action@v1.1.0
      - uses: docker/setup-buildx-action@v1.3.0
      - uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2.5.0
        with:
          push: true
          context: gcc
          file: gcc/x86_64-none-elf.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: chrissx/gcc-x86_64-none-elf:11
          build-args: |
            BINUTILS=ftp://ftp.gnu.org/gnu/binutils/binutils-2.36.1.tar.xz
            GCC=ftp://ftp.gnu.org/gnu/gcc/gcc-11.1.0/gcc-11.1.0.tar.xz
  gcc-aarch64-none-elf-11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-qemu-action@v1.1.0
      - uses: docker/setup-buildx-action@v1.3.0
      - uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2.5.0
        with:
          push: true
          context: gcc
          file: gcc/aarch64-none-elf.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: chrissx/gcc-aarch64-none-elf:11
          build-args: |
            BINUTILS=ftp://ftp.gnu.org/gnu/binutils/binutils-2.36.1.tar.xz
            GCC=ftp://ftp.gnu.org/gnu/gcc/gcc-11.1.0/gcc-11.1.0.tar.xz
  gcc-x86_64-none-elf-12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-qemu-action@v1.1.0
      - uses: docker/setup-buildx-action@v1.3.0
      - uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2.5.0
        with:
          push: true
          context: gcc
          file: gcc/x86_64-none-elf.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: chrissx/gcc-x86_64-none-elf:12
          build-args: |
            BINUTILS=ftp://ftp.gnu.org/gnu/binutils/binutils-2.36.1.tar.xz
            GCC=https://gcc.gnu.org/pub/gcc/snapshots/12-20210523/gcc-12-20210523.tar.xz
  gcc-aarch64-none-elf-12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-qemu-action@v1.1.0
      - uses: docker/setup-buildx-action@v1.3.0
      - uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2.5.0
        with:
          push: true
          context: gcc
          file: gcc/aarch64-none-elf.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: chrissx/gcc-aarch64-none-elf:12
          build-args: |
            BINUTILS=ftp://ftp.gnu.org/gnu/binutils/binutils-2.36.1.tar.xz
            GCC=https://gcc.gnu.org/pub/gcc/snapshots/12-20210523/gcc-12-20210523.tar.xz
  gcc-x86_64-none-elf-trunk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-qemu-action@v1.1.0
      - uses: docker/setup-buildx-action@v1.3.0
      - uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2.5.0
        with:
          push: true
          context: gcc
          file: gcc/x86_64-none-elf.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: chrissx/gcc-x86_64-none-elf:trunk
          build-args: |
            BINUTILS=ftp://ftp.gnu.org/gnu/binutils/binutils-2.36.1.tar.xz
            GCC=https://github.com/gcc-mirror/gcc/archive/refs/heads/master.tar.gz
  gcc-aarch64-none-elf-trunk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-qemu-action@v1.1.0
      - uses: docker/setup-buildx-action@v1.3.0
      - uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2.5.0
        with:
          push: true
          context: gcc
          file: gcc/aarch64-none-elf.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: chrissx/gcc-aarch64-none-elf:trunk
          build-args: |
            BINUTILS=ftp://ftp.gnu.org/gnu/binutils/binutils-2.36.1.tar.xz
            GCC=https://github.com/gcc-mirror/gcc/archive/refs/heads/master.tar.gz
  llvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-qemu-action@v1.1.0
      - uses: docker/setup-buildx-action@v1.3.0
      - uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2.5.0
        with:
          push: true
          file: llvm.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          tags: chrissx/llvm:latest
  tor-proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-qemu-action@v1.1.0
      - uses: docker/setup-buildx-action@v1.3.0
      - uses: docker/login-action@v1.9.0 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2.5.0
        with:
          push: true
          context: tor-proxy
          platforms: linux/amd64,linux/arm64,linux/arm,linux/ppc64le,linux/s390x
          tags: chrissx/tor-proxy:latest
  prometheus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-qemu-action@v1.1.0
      - uses: docker/setup-buildx-action@v1.3.0
      - uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2.5.0
        with:
          push: true
          context: prometheus
          platforms: linux/amd64,linux/arm64,linux/arm,linux/ppc64le,linux/s390x
          tags: chrissx/prometheus:latest
